FROM ubuntu:18.04
RUN sed -i 's/archive.ubuntu.com/mirrors.cloud.tencent.com/g; s/security.ubuntu.com/mirrors.cloud.tencent.com/g' /etc/apt/sources.list \
    && rm -f /etc/apt/apt.conf.d/docker-gzip-indexes
RUN apt update && apt install -y python python-pip && rm -rf /var/lib/apt/lists/*
RUN pip install elasticsearch mysql-python
COPY pytools/ /root/
WORKDIR /root/pytools
