version: '3'
services:
    db:
        image: docker.io/mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: xviewer_default_password
        volumes:
            - datavol:/var/lib/mysql
    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.26
        environment:
            discovery.type: single-node
        user: root
        restart: always
        deploy:
            resources:
                limits:
                    memory: 2G
        volumes:
            - esvol:/usr/share/elasticsearch/data
    app:
        build:
            context: .
        image: xviewer:latest
        restart: always
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_USER: root
            DB_PASS: xviewer_default_password
            DB_NAME: xviewer
            ES_HOST: es
            ES_INDEX: test-video-index
            ROOT_DIR: /data
            LISTEN_PORT: 9889
            KOA_APP_KEYS: xviewer
        volumes:
            - videovol:/data
volumes:
    datavol:
    esvol:
    videovol:
